#!/bin/sh

# Git hook for re-versioning simulink files on pre-commit.

PREFIX="pre-commit:"

LOCALS="hooks/locals"

# Read local vars file.
i=0
while IFS= read -r LINE
do
  VAR[$i]="$LINE"
  let "i=i+1"
done < "$LOCALS"

# Exit if already running 2018b.
if [ ${VAR[0]} = "(R2018b)" ]; then
    echo "Already running 2018b - exiting hook."
    exit
fi

# Get list of changed files.
FILELIST=$(git diff --diff-filter=d --cached --name-only)
FILESTR=$( echo "$FILELIST" | sed 's/ /\\ /g' )

echo $FILESTR > "out.test"

# Call MATLAB update script.
$("${VAR[1]}/matlab" -batch 'addpath("'$PWD'/hooks"); to2018b("'$FILELIST'");')

echo "Files successfully converted!"

exit
